export const theme = {
  colors: {
    primary: '#25D366',
    onPrimary: '#FFFFFF',
    primaryContainer: '#C8F7C5',
    onPrimaryContainer: '#00210B',
    secondary: '#0078D4',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#CCE7FF',
    onSecondaryContainer: '#001E2F',
    surface: '#FFFFFF',
    onSurface: '#1A1A1A',
    surfaceVariant: '#F5F5F5',
    onSurfaceVariant: '#666666',
    background: '#F8F9FA',
    onBackground: '#1A1A1A',
    outline: '#E0E0E0',
    error: '#DC3545',
    onError: '#FFFFFF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};